# Generated by Django 2.0.3 on 2018-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.NullBooleanField()),
            ],
        ),
    ]
