# Generated by Django 2.0.3 on 2018-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='category',
            field=models.CharField(choices=[('speed', 'Speed'), ('common', 'Common'), ('server', 'Server'), ('security', 'Security'), ('advanced_seo', 'Advanced SEO')], max_length=2),
        ),
    ]
