# Generated by Django 2.0.3 on 2018-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0005_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='Rule',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]

    atomic = False
