# Generated by Django 2.0.3 on 2018-04-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0006_auto_20180421_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
