# Generated by Django 2.0.3 on 2018-04-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0007_auto_20180421_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('status', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('speed', 'Speed'), ('common', 'Common'), ('server', 'Server'), ('security', 'Security'), ('advanced_seo', 'Advanced SEO')], max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkup.Rule'),
        ),
    ]
