# Generated by Django 2.0.3 on 2018-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0010_auto_20180422_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=200),
        ),
    ]
