# Generated by Django 2.0.3 on 2018-05-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0011_rule_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='website',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
