# Generated by Django 2.0.3 on 2018-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0012_auto_20180518_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
