# Generated by Django 2.0.3 on 2018-05-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0013_auto_20180519_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
