# Generated by Django 2.0.3 on 2018-05-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0014_auto_20180524_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('common', 'Common'), ('server', 'Server'), ('advanced_seo', 'Advanced SEO')], max_length=200),
        ),
    ]
