# Generated by Django 2.0.3 on 2018-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0015_auto_20180524_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
