# Generated by Django 2.0.3 on 2018-05-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0016_auto_20180524_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
